services:
    borisba.registerlog.listener:
        class: borisba\registerlog\event\listener
        arguments:
            - '@config'
            - '@user'
            - '@request'
            - '@log'
        tags:
            - { name: event.listener }
